feat: pass custom crf value

diff --git a/vx265 b/vx265
--- a/vx265
+++ b/vx265
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 #
-# ---------------------------------------------------------
+# 
 # Batch video encoder for X265/HEVC conversion
-# ---------------------------------------------------------
-# Author:      Rish
-# Date:        May 7, 2026
-# License:     MIT
-# ---------------------------------------------------------
+# 
+# Author: Rish
+# Date: June 9, 2026
+# License: MIT
+# 
 #
 # Colors
 YW='\e[1;33m'   # yellow
@@ -17,16 +17,16 @@ WE='\e[1;37m'   # white
 NC='\e[0m'      # normal
 
 usage() {
-    echo -e "Usage: vx265 [path/to/video directory] [Options]"
+    echo -e "Usage: vx265 [OPTION] <ARGUMENT>"
     echo -e "Options:"
     echo -e "  --mkv          Converts all .mkv files"
     echo -e "  --mp4          Converts all .mp4 files"
     echo -e "  --m4v          Converts all .m4v files"
+    echo -e "  --mp4 21       Pass a crf value (Default: 28)"
     echo -e "  -h, --help     Display this help message"
 }
 
-# Check if at least two arguments are provided
-(($# < 2)) && { usage; exit 1; }
+(($# < 1)) && { usage; exit 1; }
 
 chk_dpdc() {
     if ! command -v ffmpeg &> /dev/null; then 
@@ -39,10 +39,10 @@ main() {
     local format="$1"
     echo -e "${WE}Converting '${format^^}s' into x265 codec...\n${NC}"
 
-    for file in "$VID_DIR"/*.${format}; do
+    for file in *.${format}; do
         [[ -e "$file" ]] || { echo "No '${format^^}' files found."; return; }
         echo -e "${GY} Processing '$file'...${NC}"
-        ffmpeg -hide_banner -loglevel error -i "$file" -c:a copy -c:v libx265 "${file%.*}_new.${format}"
+        ffmpeg -hide_banner -loglevel error -i "$file" -c:a copy -c:v libx265 -crf "${CRF:-28}" "${file%.*}_new.${format}"
         sleep 5
     done
 
@@ -51,20 +51,15 @@ main() {
 
 chk_dpdc 
 
-VID_DIR="$1"
-EXTENSION="$2"
+EXT="$1"
+CRF="$2"
 
-if [[ ! -d "$VID_DIR" ]]; then
-    echo -e "${RD}E:${NC} Directory '$VID_DIR' not found."
-    exit 1
-fi
-
-case $EXTENSION in
+case $EXT in
     --mkv ) main "mkv" ;; 
     --mp4 ) main "mp4" ;;
     --m4v ) main "m4v" ;; 
     --help | -h ) usage ;;
-    *) echo -e "${RD}Invalid option:${NC} '${YW}$EXTENSION${NC}'"
+    *) echo -e "${RD}Invalid option:${NC} '${YW}$EXT${NC}'"
        echo -e "Try 'vx265 --help' for more information."
        exit 1 ;;
 esac
